<?php

namespace App\Models\News;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    protected $table = 'news';

    protected $fillable = [
        'id',
        'first_page',
        'intop',
        'ngroup',
        'view_num',
        'filename_src',
        'url',
        'filename_ico',
    ];

    protected $dates = ['dtime'];

    public $timestamps = false;


    /* route for comment */

    public function NewsCommentLink()
    {
        $model_name = 'news_comments';

        return route('admin.model', $model_name);
    }


    /* observer  */
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::saved(function ($model) {
            $model = News::withoutEvents(function () use($model) {
                /* set current path img in database */
                $filename_src = $model->filename_src;
                $filename_src = stristr($filename_src, '/');
                $filename_src = ltrim($filename_src, '/');
                $model->filename_src = $filename_src;

                /* set url slug */
                $model->url = \Str::slug($model->id. '-' . $model['NewsLang']->title);
                $model->save();

                return $model;
            });
        });
    }

    /* Relations */

    public function NewsLang()
    {
        return $this->hasOne(NewsLang::class, 'news_id');
    }

    public function NewsComment()
    {
        return $this->hasMany(NewsComment::class, 'item_id');
    }
}
